site_name: Hemlock-Big5
docs_dir: docs_md
site_dir: docs
repo_url: https://github.com/dsbowen/hemlock-big5
edit_uri: edit/master/docs_md
nav:
  - Home: index.md
  - API: api.md
theme: readthedocs
extra_css:
  - css/extra.css